version: '3.7'

# 컴퓨터들
services:

  #  컴퓨터 이름
  my-backend:
    image: asia.gcr.io/still-primer-377405/khj-project-nestjs:1.2
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/myfolder/src  
    ports:
      - 3000:3000 
    env_file:
      - ./.env.prod

  #  컴퓨터 이름
  # my_database:
  #   # platform: linux/x86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'mydocker'
  #     MYSQL_ROOT_PASSWORD: 'skdlfm12@'
  #   ports:
  #     - 3306:3306